-- 3월에 태어난 여성 회원 목록 출력하기
SELECT MEMBER_ID -- 아이디
    ,MEMBER_NAME -- 이름
    ,GENDER -- 성별
    ,DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH -- 생년월일
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL  
    AND MONTH(DATE_OF_BIRTH)='03'
    AND GENDER = 'W'
ORDER BY MEMBER_ID ASC
