-- 노선별 역 사이 거리 조회하기
SELECT ROUTE
        ,CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),"km") AS TOTAL_DISTANCE -- 총 누계거리
        ,CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),"km" ) AS AVERAGE_DISTANCE -- 평균 역 사이 거리
FROM SUBWAY_DISTANCE 
GROUP BY ROUTE 
ORDER BY ROUND(SUM(D_BETWEEN_DIST),1) DESC